## 1. If the MasterName option is specified, a sentinel-backed FailoverClient is returned.
## 2. if the number of Addrs is two or more, a ClusterClient is returned.
## 3. Otherwise, a single-node Client is returned.
redis:
  default:
    addrs:
      - ${REDIS_ADDR}
    db: 0 # Only single-node and failover clients.
    password: ${REDIS_PASSWORDS}
    #sentinel_password:
    #username:
    #max_retries: 3 # Default is 3 retries; -1 (not 0) disables retries.
    #min_retry_backoff: 8 # Default is 8 milliseconds; -1 disables backoff.
    #max_retry_backoff: 512 # Default is 512 milliseconds; -1 disables backoff.
    #dial_timeout: 5 # Default is 5 seconds.
    #read_timeout: 3 # Default is 3 seconds. Use value -1 for no timeout and 0 for default.
    #write_timeout: 0 # Default is ReadTimeout.
    #pool_fifo: false # Type of connection pool. true for FIFO pool, false for LIFO pool.
    #pool_size: 10 # Default is 10 connections per every available CPU as reported by runtime.GOMAXPROCS.
    #min_idle_conns: 1 # Minimum number of idle connections which is useful when establishing
    #max_conn_age: 0 # (Millisecond) Default is to not close aged connections.
    #pool_timeout: 0 # Default is ReadTimeout + 1 second.
    #idle_timeout: 5 # Default is 5 minutes. -1 disables idle timeout check.
    #idle_check_frequency: 1 # Default is 1 minute. -1 disables idle connections reaper, but idle connections are still discarded by the client if IdleTimeout is set.
    ########Only cluster clients.##########
    #max_redirects: # （int）Default is 3 retries.
    #read_only: #（bool）Enables read-only commands on slave nodes.
    #route_by_latency: #（bool）Allows routing read-only commands to the closest master or slave node.
    #route_randomly: #（bool）Allows routing read-only commands to the random master or slave node.
    ########Only failover clients.##########
    #master_name:
  cache:
    addrs:
      - ${REDIS_ADDR}
    db: 1
    password: ${REDIS_PASSWORDS}