definitions:
  entity.ResultJSON:
    properties:
      code:
        type: integer
      data: {}
      message:
        type: string
    type: object
  entity.ShortUrlCreateRequest:
    properties:
      domain:
        example: http://xxx.xx
        type: string
      ttl:
        type: integer
      url:
        example: http://xx.xx/a/b
        type: string
    required:
    - url
    type: object
  entity.ShortUrlCreateResponse:
    properties:
      url:
        type: string
    type: object
info:
  contact: {}
paths:
  /url:
    post:
      consumes:
      - application/json
      parameters:
      - description: UrlCreate info
        in: body
        name: root
        required: true
        schema:
          $ref: '#/definitions/entity.ShortUrlCreateRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/entity.ResultJSON'
            - properties:
                code:
                  type: integer
                data:
                  $ref: '#/definitions/entity.ShortUrlCreateResponse'
                message:
                  type: string
              type: object
      summary: Url Create
swagger: "2.0"
